### PR TITLE
ARGO-45 Configuration of pig and hadoop clients loggings

### PR DESCRIPTION
**Pull request by pkoro**
- Add section in pig log4j.properties file for Rolling File Appender
- Add reference to log4j.properties file within pig.properties file
- Add Rolling File Appender in default hadoop client logging

### CODE REVIEW

**Comment by argo-jira** [comment]
This is not the correct license

**Comment by skanct** [comment]
This is not the correct license

**Comment by pkoro** [comment]
It's the license from the pig project I believe. I can change it to our license but the file is installed from another package so I don't know if that would be a sensible approach:

```
# rpm -qf /etc/pig/conf/log4j.properties
pig-0.11.0+46-1.cdh4.7.1.p0.10.el6.noarch
```

**Comment by pkoro** [comment]
To be more exact I am adding L26 through to $ in the original file.

**Comment by pkoro** [comment]
please review /cc @skanct, @themiszamani

**Pull request merged**
