### PR TITLE
ARGO-243 WebUI Role addition

### PR DESCRIPTION
**Pull request by pkoro**
# Description

This PR translates the [web ui setup guide][l1] into Ansible role and play. 

# Implementation (steps)

- [x] Added new role with name `webui`
- [x] Added new playbook in top level directory (`webui.yml`)
- [x] Service should be started via Ansible role

# WIP State

The PR is currently in WIP state because an error is generated when trying to start the service. The error is [here][l2]. An initial investigation has began and if appropriate an issue will be opened to update the guide. 

[l1]: https://github.com/ARGOeu/argo-egi-web
[l2]: http://fpaste.org/288834/14471658/raw/

### CODE REVIEW

**Comment by pkoro** [comment]
Problem fixed. After investigation with the help of @cyril1er It was due to wrong certificates path. Default web interface has also been changed to http following the same discussion.

**Comment by pkoro** [comment]
please review /cc @themiszamani @dpavlos

**Comment by themiszamani** [comment]
Tested. +1

**Comment by dpavlos** [comment]
+1

**Pull request merged**
