### PR TITLE
ARGO-336 Add swagger deployment for both argo-web-api and argo-messaging

### PR DESCRIPTION
**Pull request by kaggis**
- [x] Install Apache 
- [x] Create two /html dirs (/argo-web-api and /argo-messaging) for hosting 2 swagger ui's
- [x] Deploy x2 swagger-ui on the two directories
- [x] Grab x2 swagger.yaml (argo-web-api & messaging) from respective repos
- [x] Transform x2  swagger.yaml -> swagger.json
- [x] Change swagger definition references on each swagger-ui index.html

### CODE REVIEW

**Comment by kaggis** [comment]
please review 
/cc @pkoro @dpavlos

**Comment by pkoro** [comment]
@kaggis one request for changes: It's better not to add the role into the playbook webapi.yml (at least for the moment) and not to include the variables in the group_vars/{{group}} file. The variables should better be hosted inside the file `roles/swagger/defaults/main.yml`. Also note that a few variables are not defined at the moment, so make sure all variables used are defined with exemplary values in the aforementioned defaults file.

**Comment by kaggis** [comment]
- [x] Added swagger related vars in role /swagger/defaults/main.yml
- [x] Use swagger role, in new swagger playbook

please review /cc @pkoro

**Comment by pkoro** [comment]
+1

**Pull request merged**
