### PR TITLE
ARGO-389 Nagios configurations

### PR DESCRIPTION
**Pull request by dpavlos**
- Various fixes and modifications in ansible configs.
- Includes the functionality for sensitive configuration files proposed in this PR https://github.com/grnet/argo-ansible-deploy/pull/24

### CODE REVIEW

**Comment by dpavlos** [comment]
Left the squash for later in case we need to change something after the review.
Please review /cc @pkoro @themiszamani

**Comment by pkoro** [comment]
I get the private_files link. It's neat and nice. But I would propose to make two changes. 

1) Correct the link path (it should be just `../private_files`)
2) Add conditional in action using the private file or within the template itself, whichever is more convenient.

**Comment by dpavlos** [comment]
@pkoro Good catch! Fixed.

**Comment by pkoro** [comment]
+1 . please squash your changes into one commit.

**Comment by pkoro** [comment]
+1

**Pull request merged**
